"""Initial migration with enhanced blog features

Revision ID: 19d9981a6846
Revises: 
Create Date: 2025-06-25 16:48:52.496983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d9981a6846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('excerpt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))
        batch_op.drop_index(batch_op.f('ix_tag_name'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('last_modified')
        batch_op.drop_column('is_published')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('excerpt')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
